### ISSUE TITLE
Criação das models

### ISSUE THREAD

**Issue by wagnermor** [CarteiraDoZe/backEnd_carteiraDoZe#2]
- [x] model/usuario
- [x] model/carteira !!!! RETIRAR o atributo totalKm E ADICIONAR os atributos Diária e ValorEntrega na tabela Carteira
- [x] mode/movimentação !!!! ADICIONAR o atributo descrição
- [x] model/transação !!!! RETIRAR atributo descrição
- [x] model/quilometragem
![image](https://user-images.githubusercontent.com/47096330/220133530-000b5a52-db2e-4291-891d-74e7b8f8e5d7.png)

**Comment by ChrisPCruz99** [comment]
Criação das Models com as respectivas mudanças de diagramação finalizada.
